import React, { Suspense } from 'react'
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button"
import Link from 'next/link';
import { Input } from '@/components/ui/input';
import { Metadata } from 'next';
import { TotalAmount } from '@/lib/totalAmount';
import { allReturnAmount } from '@/lib/allReturnAmount';
import { getStatus } from '@/lib/getStatus';
import { getSearchDonor } from '@/lib/SearchDonor';
import SearchBox from '@/components/SearchBox';

export const metadata: Metadata = {
	title: "Donor List",
	description: "Generated by Rakibul hasan",
};

async function DonorList({ searchParams }: {
	searchParams?: {
		search?: string,
		page?: string,
	}
}) {
	const query = searchParams?.search || "all";
	try {
		const result = await getSearchDonor(query);
		const donors = result?.slice(0, 5);


		return (
			<TableBody>
				{
					donors.map((item, index: number) => (
						<TableRow key={index}>
							<TableCell className="font-medium">{item.code}</TableCell>
							<TableCell className="font-medium uppercase">{item.name}</TableCell>
							<TableCell className="font-medium uppercase" >{TotalAmount(item.status, item.username, item.amount)}</TableCell>
							<TableCell className="font-medium uppercase" >{allReturnAmount(item.status, item.username)}</TableCell>
							<TableCell className="font-medium uppercase">{getStatus(item?.status)}</TableCell>
							<TableCell className="font-medium uppercase">
								<Button className='bg-color-sub' size={"sm"} asChild>
									<Link href={`donor-and-lenders/${item.username}`}>DETAILS</Link>
								</Button>

							</TableCell>
						</TableRow>
					))
				}
			</TableBody>
		)
	} catch (error) {
		throw new Error("Data fetch failed");
	}
};

function SearchBarFallback() {
	return <>placeholder</>
}


async function page({ searchParams }: {
	searchParams?: {
		search?: string,
		page?: string,
	}
}) {
	return (
		<div className='flex flex-col'>
			<Suspense fallback={<SearchBarFallback />}>
				<SearchBox />
			</Suspense>
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead>CODE</TableHead>
						<TableHead className='w-[300px]'>NAME</TableHead>
						<TableHead>AMOUNT</TableHead>
						<TableHead>RETURNED AMOUNT</TableHead>
						<TableHead>TYPE</TableHead>
						<TableHead>DETAILS</TableHead>
					</TableRow>
				</TableHeader>
				<Suspense fallback={<h2 className=' text-center p-4'>Loading...</h2>} >
					<DonorList searchParams={searchParams} />
				</Suspense>
			</Table>

		</div>
	)
}

export default page