import ABoutSidebar from "@/components/AboutSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "আমাদের সম্পর্কে",
  description: "Generated by Arafat Foundation",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="bg-[#FCFCFD]">
      <div className="md:mx-20 bg-[#FCFCFD] md:my-4 py-2">
        <div className="flex bg-[#FCFCFD] md:flex-row flex-col gap-4 mt-32">
          <div className="basis-1/5">
            <ABoutSidebar />
          </div>
          <div className=" md:px-2 bg-[#FCFCFD] rounded-md border-[2px] px-1 py-2 basis-4/5 ">
            {children}
          </div>
        </div>
      </div>
    </section>
  );
}
