import HeaderContent from "@/components/HeaderContent";
import HeaderSlider from "@/components/HeaderSlider";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";



export const metadata: Metadata = {
	title: "কর্জে হাসানা",
	description: "Generated by Arafat Foundation",
};

async function getDonors() {
	try {
		const res = await fetch("https://arafatfoundation.org/api/donor");
		if (!res.ok) {
			throw new Error("Network response was not ok");
		}
		const data = await res.json();
		return data;
	} catch (error) {
		console.log("Error fetching donors:", error);


	}
}

export default async function KarzeHasanaLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const donors = await getDonors();
	return (
		<section className="bg-[#FCFCFD]">
			<HeaderSlider />
			<HeaderContent />
			<div className="md:mx-20 md:my-4 my-2">
				<div className="flex md:flex-row flex-col gap-4">
					<div className="basis-1/5">
						<Sidebar donors={donors} />
					</div>
					<div className=" md:px-2 bg-white  rounded-md border-[2px] px-1 py-2 basis-4/5">{children}</div>
				</div>
			</div>
		</section>
	);
}
