import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";



export const metadata: Metadata = {
	title: "Karze Hasana",
	description: "Generated by Arafat Foundation",
};

export default function KarzeHasanaLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<section className="mx-24 my-4">
			<div className="flex flex-row gap-2">
				<div className=" basis-1/4">
					<Sidebar />
				</div>
				<div className="border-2 basis-3/4">{children}</div>
			</div>
		</section>
	);
}
