import HeaderContent from "@/components/HeaderContent";
import HeaderSlider from "@/components/HeaderSlider";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";



export const metadata: Metadata = {
	title: "কর্জে হাসানা",
	description: "Generated by Arafat Foundation",
};

async function getDonors() {
	try {
		const res = await fetch("https://af-admin.vercel.app/api/donor", {
			next: { revalidate: 3600 * 60 * 24 },
		});
		const data = await res.json();
		console.log({ data });

		return data || [];
	} catch (error) {
		console.log("Error fetching donors:", error);
		return [];
	}
}

export default async function KarzeHasanaLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const donors = await getDonors();
	return (
		<section className="bg-[#FCFCFD]">
			<HeaderSlider />
			<HeaderContent />
			<div className="md:mx-20 md:my-4 my-2">
				<div className="flex md:flex-row flex-col gap-4">
					<div className="basis-1/5">
						<Sidebar donors={donors} />
					</div>
					<div className=" md:px-2 bg-white  rounded-md border-[2px] px-1 py-2 basis-4/5">{children}</div>
				</div>
			</div>
		</section>
	);
}
