import React, { Suspense } from 'react'
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button"
import Link from 'next/link';
import { BranchIProps } from '@/types';
import { unstable_noStore } from 'next/cache';
import { Input } from '@/components/ui/input';
import { Metadata } from 'next';
import SearchBox from '@/components/SearchBox';
import { getSearchBranch } from '@/lib/SearchBranch';

export const metadata: Metadata = {
	title: "Branch List",
	description: "Generated by Arafat foundation",
};

function SearchBarFallback() {
	return <>placeholder</>
}

async function BranchList({ searchParams }: {
	searchParams?: {
		search?: string,
		page?: string,
	}
}) {
	const query = searchParams?.search || "all";
	try {

		const branches = await getSearchBranch(query);
		return (
			<TableBody>
				{
					branches?.slice(0, 5)?.map((item, index: number) => (
						<TableRow key={index}>
							<TableCell className="font-medium">{item.code}</TableCell>
							<TableCell className="font-medium uppercase">{item.branchName}</TableCell>
							<TableCell className="font-medium uppercase" >{item.district}</TableCell>
							<TableCell className="font-medium uppercase">{item.ps}</TableCell>
							<TableCell className="font-medium uppercase">
								<Button className='bg-color-sub' size={"sm"} asChild>
									<Link href={`branches/${item.username}`}>DETAILS</Link>
								</Button>

							</TableCell>
						</TableRow>
					))
				}
			</TableBody>
		)
	} catch (error) {
		throw new Error("data fetch failed");
	}
};



async function page({ searchParams }: {
	searchParams?: {
		search?: string,
		page?: string,
	}
}) {
	return (
		<div className='flex flex-col'>
			<Suspense fallback={<SearchBarFallback />}>
				<SearchBox />
			</Suspense>
			<Table>
				<TableHeader>
					<TableRow>
						<TableHead>CODE</TableHead>
						<TableHead className='md:w-[300px]'>BRANCH</TableHead>
						<TableHead>DISTRICT</TableHead>
						<TableHead>PS(TANA)</TableHead>
						<TableHead>DETAILS</TableHead>
					</TableRow>
				</TableHeader>
				<Suspense fallback={<h2 className=' text-center p-4'>Loading...</h2>} >
					<BranchList searchParams={searchParams} />
				</Suspense>
			</Table>

		</div>
	)
}

export default page