import GallerySidebar from "@/components/GallerySidebar";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
import { getGallery } from "@/lib/getGallery";
import { CategoryIProps } from "@/types";
import { Metadata } from "next";
import { unstable_noStore } from "next/cache";
import Image from "next/image";
import { Suspense } from "react";
import icon from "../../../public/divider.svg";
import {
  GalleryGridSkeleton,
  SidebarSkeleton,
  LoadingSpinner
} from "./loading";

export const metadata: Metadata = {
  title: "গ্যালারি",
  description: "Generated by Rakibul hasan ",
};

// Optimized Image component with blur loading
function OptimizedImage({
  src,
  alt,
  width,
  height,
  className,
  priority = false,
}: {
  src: string;
  alt: string;
  width: number;
  height: number;
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
      src={src}
      className={className}
      width={width}
      height={height}
      alt={alt}
      placeholder="blur"
      blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABAUGIWGRkqGx0f/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECEgMRkf/aAAwDAQACEQMRAD8AltJagyeH0AthI5xdrLcNM91BF5pX2HaH9bcfaSXWGaRmknyJckliyjqTzSlT54b6bk+h0R//2Q=="
      priority={priority}
    />
  );
}

async function GalleryList({ query }: { query: string }) {
  unstable_noStore();
  const data = await getGallery(query);

  if (!data || data.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-gray-500">
        <svg
          className="w-16 h-16 mb-4 text-gray-300"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
          />
        </svg>
        <p className="text-lg font-medium">কোন ছবি পাওয়া যায়নি</p>
        <p className="text-sm">এই ক্যাটেগরিতে কোন কন্টেন্ট নেই</p>
      </div>
    );
  }

  return (
    <div className="grid py-2 md:px-1 px-1 grid-cols-3 content-stretch gap-2">
      {data.map((item, index) => (
        <Dialog key={`${item.id || index}-${item.category}`}>
          <DialogTrigger asChild>
            <button className="flex justify-center md:w-[280px] md:h-[200px] w-[100px] h-[80px] p-2 group focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 rounded-lg">
              {item.category === "video" ? (
                <div className="md:flex hidden relative overflow-hidden rounded-md w-full h-full">
                  <iframe
                    width="100%"
                    height="100%"
                    className="object-fill rounded transition-opacity duration-300 group-hover:opacity-90"
                    src={`${item.content}`}
                    title="YouTube video player"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowFullScreen
                    loading="lazy"
                  ></iframe>
                  {/* Video overlay */}
                  <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors duration-300 pointer-events-none"></div>
                </div>
              ) : (
                <div className="relative overflow-hidden rounded-md w-full h-full">
                  <OptimizedImage
                    src={item.content}
                    className="rounded-md transition-all duration-300 group-hover:opacity-90 group-hover:scale-105 w-full h-full object-cover"
                    width={308}
                    height={208}
                    alt={item.category}
                  />
                  {/* Image overlay */}
                  <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors duration-300 pointer-events-none"></div>
                </div>
              )}
            </button>
          </DialogTrigger>
          <DialogContent className="w-full flex justify-center items-center max-w-4xl">
            <div className="relative max-w-full max-h-[80vh] overflow-hidden rounded-md">
              {item.category === "video" ? (
                <iframe
                  width="800"
                  height="450"
                  className="rounded-md"
                  src={`${item.content}`}
                  title="YouTube video player"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                  allowFullScreen
                ></iframe>
              ) : (
                <OptimizedImage
                  src={item.content}
                  className="rounded-md w-auto h-auto max-w-full max-h-[80vh] object-contain"
                  width={800}
                  height={600}
                  alt={item.category}
                  priority={true}
                />
              )}
            </div>
          </DialogContent>
        </Dialog>
      ))}
    </div>
  );
}

async function page({
  searchParams,
}: {
  searchParams?: {
    type?: string;
    page?: string;
  };
}) {
  unstable_noStore();

  let res = await fetch("https://af-admin.vercel.app/api/category", {
    next: { revalidate: 0 } // Cache for 1 minute
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data list");
  }

  const data: CategoryIProps[] = await res.json();
  const query = searchParams?.type || "all";

  return (
    <section className="bg-[#FCFCFD] mt-40 min-h-screen">
      <div className="my-2 md:mx-20 mx-2 md:my-4">
        <h1 className="py-2 text-4xl font-semibold text-center text-color-main">
          গ্যালারী
        </h1>
        <div className="flex flex-col items-center justify-center gap-2 py-3">
          <Image src={icon} alt="icon" />
        </div>
        <div className="flex flex-col gap-4 md:flex-row">
          <Suspense fallback={<SidebarSkeleton />}>
            <div className="basis-1/5">
              <GallerySidebar data={data} />
            </div>
          </Suspense>
          <div className="md:p-1 bg-white rounded-md border-[2px] basis-4/5 min-h-[400px]">
            <Suspense
              fallback={
                <div className="flex flex-col items-center justify-center py-8">
                  <LoadingSpinner size="lg" />
                  <p className="mt-4 text-gray-500">ছবি লোড হচ্ছে...</p>
                  <GalleryGridSkeleton count={6} />
                </div>
              }
            >
              <GalleryList query={query} />
            </Suspense>
          </div>
        </div>
      </div>
    </section>
  );
}

export default page;