import GallerySidebar from '@/components/GallerySidebar'
import React, { Suspense } from 'react'
import icon from "../../../public/divider.svg"
import Image from 'next/image'
import {
	Dialog,
	DialogContent,
	DialogTrigger,
} from "@/components/ui/dialog"
import { getGallery } from '@/lib/getGallery'
import { unstable_noStore } from 'next/cache'
import { Metadata } from 'next'
import { CategoryIProps } from '@/types'

export const metadata: Metadata = {
	title: "গ্যালারি",
	description: "Generated by Rakibul hasan ",
};

async function GalleryList({ query }: { query: string }) {
	unstable_noStore();
	const data = await getGallery(query);
	return (
		<div className="grid py-2 md:px-1 px-1 grid-cols-3 content-stretch gap-2">
			{
				data.map((item, index) => (
					<Dialog key={index}>
						<DialogTrigger>
							<div className="flex justify-center md:w-[280px] md:h-[200px] w-[100px] h-[80px] p-2 ">
								{
									item.category === "video" ? <iframe width="308" height="200" className='object-fill px-2 rounded' src={`${item.content}`} title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen ></iframe> : <Image sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" src={item.content} className=' rounded-md hover:opacity-90' width={308} height={208} alt={item.category} />
								}
							</div>
						</DialogTrigger>
						<DialogContent className='w-full flex justify-center items-center '>
							<Image sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" src={item.content} className=' rounded-md hover:opacity-90' width={500} height={500} alt={item.category} />
						</DialogContent>
					</Dialog>
				))
			}
		</div>

	)
}


async function page({ searchParams }: {
	searchParams?: {
		type?: string,
		page?: string,
	}
}) {
	unstable_noStore();
	let res = await fetch('https://af-admin.vercel.app/api/category');
	if (!res.ok) {
		throw new Error("Failed to fetch data list");
	};
	const data: CategoryIProps[] = await res.json();
	const query = searchParams?.type || "all";
	return (
		<section className="bg-[#FCFCFD]">
			<div className="my-2 md:mx-20 mx-2 md:my-4">
				<h1 className="py-2 text-4xl font-semibold text-center text-color-main">গ্যালারী</h1>
				<div className='flex flex-col items-center justify-center gap-2 py-3 '>
					<Image src={icon} alt='icon' />
				</div>
				<div className="flex flex-col gap-1 md:flex-row">
					<Suspense fallback={<h2>Loading...</h2>}>
						<div className="basis-1/5">
							<GallerySidebar data={data} />
						</div>
					</Suspense>
					<div className=" md:p-1 bg-white  rounded-md border-[2px] basis-4/5">
						<Suspense fallback={<h2>Loading...</h2>}>
							<GalleryList query={query} />
						</Suspense>
					</div>
				</div>
			</div>
		</section>
	)
}

export default page
