import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Anek_Bangla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arafat Foundation",
  description: "Generated by Arafat Foundation",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
