import type { Metadata } from "next";
import { Anek_Bangla as FontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ContextProvider } from "@/components/ContextProvider";
import TanStackProvider from "@/components/TanStackProvider";
import { Toaster } from "react-hot-toast";
import { ChevronUpCircle } from 'lucide-react';
import { cn } from "@/lib/utils";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "আরাফাত ফাউন্ডেশন",
  description: "Generated by Rakibul hasan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen  relative antialiased",
        fontSans.className
      )} >
        <section id="top">
          <TanStackProvider>
            <ContextProvider>
              <Navbar />
              <NextSSRPlugin
                routerConfig={extractRouterConfig(ourFileRouter)}
              />
              {children}
              <SpeedInsights />
              <Toaster />
              <Footer />
              <div className="fixed z-10 bg-gray-100 rounded-full  right-8 bottom-10">
                <a className="" href="#top"><ChevronUpCircle size={40} /> </a>
              </div>
            </ContextProvider>
          </TanStackProvider>
        </section>
      </body>
    </html>
  );
}
