import type { Metadata } from "next";
import { Anek_Bangla as FontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ContextProvider } from "@/components/ContextProvider";
import TanStackProvider from "@/components/TanStackProvider";
import { Toaster } from "react-hot-toast";
import { ChevronUpCircle } from 'lucide-react';
import { cn } from "@/lib/utils";
import { SpeedInsights } from "@vercel/speed-insights/next"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "আরাফাত ফাউন্ডেশন",
  description: "Generated by Rakibul hasan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen  bg-slate-50 relative antialiased",
        fontSans.className
      )} >
        <TanStackProvider>
          <ContextProvider>
            <Navbar />
            {children}
            <SpeedInsights />
            <Toaster />
            <Footer />
            <div className=" fixed right-8 z-10 bottom-10 bg-gray-100 rounded-full">
              <a className="" href="#top"><ChevronUpCircle size={40} /> </a>
            </div>
          </ContextProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
