import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "শিশুর দায়িত্ব নিন",
  description: "Generated by Arafat Foundation",
};

export default function OurProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="bg-[#FCFCFD]">
      <div className="md:px-20 md:py-4 py-2 mt-36">{children}</div>
    </section>
  );
}
