import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ব্লগ",
  description: "Generated by Arafat Foundation",
};

export default function BlogsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="bg-[#FCFCFD] mt-36">
      <div className="md:px-20 md:py-4 py-2 mx-2">{children}</div>
    </section>
  );
}
