import IncomeAndExpensesSidebar from "@/components/IncomeAndExpensesSidebar";
import type { Metadata } from "next";



export const metadata: Metadata = {
    title: "ব্যায়ের হিসাব ",
    description: "Generated by Arafat Foundation",
};

export default function IncomeAndExpensesLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section className="bg-[#FCFCFD]">
            <div className="md:mx-20 md:my-4 my-2">
                <div className="flex md:flex-row flex-col gap-4">
                    <div className="basis-1/5">
                        <IncomeAndExpensesSidebar />
                    </div>
                    <div className=" md:px-2 bg-white  rounded-md border-[2px] px-1 py-2 basis-4/5">{children}</div>
                </div>
            </div>
        </section>
    );
}
