import ExpensesDetails from '@/components/ExpensesDetails'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "ব্যায়ের হিসাব ",
    description: "Generated by Arafat Foundation",
};

function page() {
    return (
        <div>
            <ExpensesDetails />
        </div>
    )
}

export default page